backend:
  name: github
  repo: naveedehmad/website
  branch: master

media_folder: "public/images"
publish_mode: editorial_workflow

collections:
  - name: "page"
    label: "Page"
    folder: "src/pages"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown"}
